version: "3"
services:
  driver-did-btcr:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-driver-did-btcr
    ports:
      - "8081:8081"
  driver-did-sov:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-driver-did-sov
    ports:
      - "8082:8082"
  driver-did-stack:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-driver-did-stack
    ports:
      - "8084:8084"
  driver-did-uport:
    image: chrislun/uni-resolver-driver-did-uport
    ports:
      - "8083:8081"
  uni-resolver-web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-uni-resolver-web
    ports:
      - "8080:8080"

