openapi: 3.0.0
servers:
  - url: /1.0/
info:
  description: Universal Resolver
  version: "1.0.0"
  title: Universal Resolver
  contact:
    email: markus@danubetech.com
paths:
  /identifiers/{identifier}:
    get:
      summary: Resolve a DID.
      description:
        <p>This endpoint resolves a DID. As input it takes the DID plus resolution options. The output is a DID
        document
        in one of the supported representations, plus metadata.</p>
        <p>See the <a href="https://w3c-ccg.github.io/did-resolution/">DID Resolution</a>
        specification for additional details.</p>
      operationId: resolve
      parameters:
        - in: path
          required: true
          name: identifier
          schema:
            type: string
          description: The DID to be resolved.
          examples:
            example1:
              value: did:sov:builder:VbPQNHsvoLZdaNU7fTBeFx
              description: A DID using the `sov` method.
        - in: header
          required: false
          name: Accept
          schema:
            type: string
          description: The requested media type of the DID document representation or DID resolution result.
          examples:
            application/did+json:
              value: application/json
              description: Media type of a DID document (JSON representation). See <a href="https://www.w3.org/TR/did-core/#json">https://www.w3.org/TR/did-core/#json</a>.
            application/did+ld+json:
              value: application/did+ld+json
              description: Media type of a DID document (JSON-LD representation). See <a href="https://www.w3.org/TR/did-core/#json-ld">https://www.w3.org/TR/did-core/#json-ld</a>.
            application/ld+json;profile="https://w3c-ccg.github.io/did-resolution/":
              value: application/ld+json;profile="https://w3c-ccg.github.io/did-resolution/"
              description: Media type of a DID resolution result (JSON-LD representation). See <a href="https://w3c-ccg.github.io/did-resolution/#did-resolution-result">https://w3c-ccg.github.io/did-resolution/#did-resolution-result</a>.
      responses:
        '200':
          description: successfully resolved!
          content:
            application/did+json:
              schema:
                type: object
                description: The DID document (JSON representation).
                example: {
                  "id": "did:sov:builder:VbPQNHsvoLZdaNU7fTBeFx",
                  "verificationMethod": [
                    {
                      "type": "Ed25519VerificationKey2018",
                      "id": "did:sov:builder:VbPQNHsvoLZdaNU7fTBeFx#key-1",
                      "publicKeyBase58": "GasrpJqMo3W9KApN4Dh62cGhYG24xhwNnCgqEKEiTKe6"
                    },
                    {
                      "type": "X25519KeyAgreementKey2019",
                      "id": "did:sov:builder:VbPQNHsvoLZdaNU7fTBeFx#key-agreement-1",
                      "publicKeyBase58": "DUmxMDUXFTZLLdxupWFzStfdzh31XgpeoGLFL4ke8AZK"
                    }
                  ],
                  "authentication": [
                    "did:sov:builder:VbPQNHsvoLZdaNU7fTBeFx#key-1"
                  ],
                  "assertionMethod": [
                    "did:sov:builder:VbPQNHsvoLZdaNU7fTBeFx#key-1"
                  ],
                  "keyAgreement": [
                    "did:sov:builder:VbPQNHsvoLZdaNU7fTBeFx#key-agreement-1"
                  ]
                }
            application/did+ld+json:
              schema:
                type: object
                description: The DID document (JSON-LD representation).
                example: {
                  "@context": [
                    "https://www.w3.org/ns/did/v1",
                    "https://w3id.org/security/suites/ed25519-2018/v1",
                    "https://w3id.org/security/suites/x25519-2019/v1"
                  ],
                  "id": "did:sov:builder:VbPQNHsvoLZdaNU7fTBeFx",
                  "verificationMethod": [
                    {
                      "type": "Ed25519VerificationKey2018",
                      "id": "did:sov:builder:VbPQNHsvoLZdaNU7fTBeFx#key-1",
                      "publicKeyBase58": "GasrpJqMo3W9KApN4Dh62cGhYG24xhwNnCgqEKEiTKe6"
                    },
                    {
                      "type": "X25519KeyAgreementKey2019",
                      "id": "did:sov:builder:VbPQNHsvoLZdaNU7fTBeFx#key-agreement-1",
                      "publicKeyBase58": "DUmxMDUXFTZLLdxupWFzStfdzh31XgpeoGLFL4ke8AZK"
                    }
                  ],
                  "authentication": [
                    "did:sov:builder:VbPQNHsvoLZdaNU7fTBeFx#key-1"
                  ],
                  "assertionMethod": [
                    "did:sov:builder:VbPQNHsvoLZdaNU7fTBeFx#key-1"
                  ],
                  "keyAgreement": [
                    "did:sov:builder:VbPQNHsvoLZdaNU7fTBeFx#key-agreement-1"
                  ]
                }
            application/ld+json;profile="https://w3c-ccg.github.io/did-resolution/":
              schema:
                $ref: '#/components/schemas/ResolutionResult'
        '400':
          description: invalid input!
        '410':
          description: successfully resolved (deactivated)!
          content:
            application/did+json:
              schema:
                type: object
                description: The deactivated DID document (JSON representation).
            application/did+ld+json:
              schema:
                type: object
                description: The deactivated DID document (JSON-LD representation).
            application/ld+json;profile="https://w3c-ccg.github.io/did-resolution/":
              schema:
                $ref: '#/components/schemas/ResolutionResult'
        '500':
          description: error!
  /properties:
    get:
      summary: Returns a map of properties of the resolver.
      operationId: universalResolverGetProperties
      responses:
        '200':
          description: Success.
          content:
            application/did+json:
              schema:
                type: object
                description: A map of properties.
  /methods:
    get:
      summary: Returns a list of supported DID methods.
      operationId: universalResolverGetMethods
      responses:
        '200':
          description: Success.
          content:
            application/did+json:
              schema:
                type: array
                items:
                  type: string
                description: The list of supported DID methods.
                example: ["btcr","sov","v1","key"]
  /testIdentifiers:
    get:
      summary: Returns a list of test identifiers that can be resolved.
      operationId: universalResolverGetTestIdentifiers
      responses:
        '200':
          description: Success.
          content:
            application/did+json:
              schema:
                type: object
                description: A map of test identifiers, grouped by DID method.
                example: { "btcr": ["did:btcr:xz35-jznz-q9yu-ply", "did:btcr:xkrn-xz7q-qsye-28p"], "sov": ["did:sov:WRfXPg8dantKVubE3HX8pw"] }
components:
  schemas:
    ResolutionResult:
      description: The DID resolution result.
      type: object
      additionalProperties: false
      properties:
        didDocument:
          type: object
          example: {
  "@context": "https://www.w3.org/ns/did/v1",
  "id": "did:sov:WRfXPg8dantKVubE3HX8pw",
  "verificationMethod": [
    {
      "id": "did:sov:WRfXPg8dantKVubE3HX8pw#key-1",
      "type": "Ed25519VerificationKey2018",
      "publicKeyBase58": "H3C2AVvLMv6gmMNam3uVAjZpfkcJCwDwnZn6z3wXmqPV"
    }
  ]
}
        didResolutionMetadata:
          type: object
        didDocumentMetadata:
          type: object
