name: CI/CD Workflow for universal-resolver

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master 
    - name: Smoke Test
      uses:  ./ci/smoke-test
