name: Build/Deploy workflow

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker Build and Push
      uses: ./ci/docker-build-push
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        DOCKER_FILE: resolver/java/uni-resolver-web/docker/Dockerfile
        CONTAINER_TAG: universalresolver/uni-resolver-web:latest
    - name: Deploy to AWS
      uses: ./ci/deploy-k8s-aws
      env:
        KUBE_CONFIG_DATA: ${{secrets.KUBE_CONFIG_DATA}}
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        RPC_URL_TESTNET: ${{secrets.RPC_URL_TESTNET}}
        RPC_CERT_TESTNET: ${{secrets.RPC_CERT_TESTNET}}
    - name: Sleep for 120 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '120s'
    - name: Smoke Test
      uses: ./ci/smoke-tests
      with:
        host: http://dev.uniresolver.io
